import { ClerkProvider } from '@clerk/nextjs'
import { Navigation } from '@components/navigation'
import TanstackProvider from '@providers/TanstackProvider'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Teste',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="dark">
        <body className="min-h-screen">
          <TanstackProvider>
            <Navigation />

            <div className="flex justify-center items-center p-24">
              {children}
            </div>
          </TanstackProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
